name: csimpact
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jinja2=3.1.4
  - lifelines=0.27.7
  - matplotlib=3.8.4
  - numpy=1.26.4
  - pandas=2.2.2
  - pyarrow=15.0.2
  - polars=0.20.16
  - seaborn=0.13.2
  - gensim=4.3.2
  - scikit-learn=1.4.2
  - scipy=1.10.1
  - spacy=3.7.4
  - ipykernel